[package]
name = "puddle"
version = "0.1.0"
authors = ["Max Willsey <me@mwillsey.com>"]

[dependencies]
serde = "1.0"
serde_derive = "1.0"
serde_yaml = "0.7"
serde_json = "1.0"
lazy_static = "1.0"
iron = "0.6"

[dev-dependencies]
proptest = "0.4"
glob = "0.2"