[package]
name = "puddle-core"
version = "0.1.0"
authors = ["Max Willsey <me@mwillsey.com>"]
license = "MIT"
edition = "2018"

[features]
# only works with --target armv7-unknown-linux-gnueabihf
pi = ["rppal"]
vision = []

[profile.release]
debug = true

# FIXME put this back
# [[bin]]
# name = "puddle-server"

[[bin]]
name = "pi-test"
required-features = ["pi"]

[[bin]]
name = "vision-test"
required-features = ["vision"]

[dependencies]

rand = "0.6.1"

serde = "^1.0"
serde_derive = "^1.0"
serde_json = "^1.0"

jsonrpc-core = "9"
jsonrpc-http-server = "9"
jsonrpc-macros = "9"
hyper-staticfile = "0.3.0"

structopt = "0.2"
derive_more = "0.14"

log = "^0.4.1"

crossbeam = "0.3.2"
env_logger = "^0.5.3"

# union-find
ena = "0.11"

# kuhn-munkres
pathfinding = "0.7"

float-ord = "0.2.0"

nalgebra = "0.15"
ncollide2d = "0.16"

matches = "0.1"
petgraph = "0.4"

# faster hashtables
hashbrown = "0.1"

rppal = {version = "0.10.0", optional = true}

[dev-dependencies]
glob = "^0.2"
matches = "0.1"

[build-dependencies]
cc = "1.0"
